# Generated by Django 4.1.7 on 2023-07-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='room',
        ),
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ManyToManyField(null=True, to='api.room'),
        ),
    ]
