# Generated by Django 4.1.7 on 2023-07-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_participant_room_participant_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='room',
            new_name='rooms',
        ),
    ]
