# Generated by Django 4.1.7 on 2023-07-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_room_participant_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='rooms',
        ),
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
    ]
