# Generated by Django 4.1.7 on 2023-07-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_participant_rooms_participant_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='participant',
        ),
    ]
